cacheFolder: "./.yarn/cache"
cacheMigrationMode: "match-spec"
checksumBehavior: "throw"
cloneConcurrency: 2
compressionLevel: 3
defaultProtocol: "npm:"
enableColors: true
enableConstraintsChecks: true
enableGlobalCache: true
enableProgressBars: true
enableTimers: true
globalFolder: "../.yarn/berry"
injectEnvironmentFiles: ["apps/web-app/.env.local"]
nodeLinker: "pnpm"
winLinkType: "symlinks"
progressBarStyle: "jack"
pnpMode: "loose"